# Auto-generated. Do not edit.
# Generated at: 2026-01-10 19:23:59

set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/controller/SC.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/controller/controller.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/controller/counter_4bit_sync.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/controller/isr_decoder.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/MDR/MDR.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/MDR/four_input_multiplexer_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/MDR/four_input_multiplexer_1bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/bus/bus_A.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/bus/bus_B.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/bus/bus_S.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/bus/or_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/shifter/shifter.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/datapath/shifter/shifter_module.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/interface/if_SC.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/interface/if_counter_4bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/lib/itf.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/lib/run.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/lib/v_chatter.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/primitives/tristate.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/primitives/v_dff_async.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/primitives/v_jkff_async.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/primitives/v_reg16.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/register/GPR.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/register/switchable_register.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/holding_circuit_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/holding_circuit_1bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_and_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_and_1bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_or_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_or_1bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_tristate_16bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/modules/transfer/transfer_tristate_1bit.v"
set_global_assignment -name VERILOG_FILE "SU-CSexpC-Final-A5/src/top.v"
